from __future__ import annotations

from backend.trading.engine.core.models import EngineContext


def build_engine_context(
    *,
    symbol: str,
    price: float,
    market_mode: str = "UNKNOWN",
    direction_policy: str = "UNKNOWN",
    box_state: str = "UNKNOWN",
    bb_state: str = "UNKNOWN",
    box_low: float | None = None,
    box_high: float | None = None,
    bb20_up: float | None = None,
    bb20_mid: float | None = None,
    bb20_dn: float | None = None,
    bb44_up: float | None = None,
    bb44_mid: float | None = None,
    bb44_dn: float | None = None,
    ma20: float | None = None,
    ma60: float | None = None,
    ma120: float | None = None,
    ma240: float | None = None,
    ma480: float | None = None,
    support: float | None = None,
    resistance: float | None = None,
    trendline_value: float | None = None,
    volatility_scale: float | None = None,
    metadata: dict | None = None,
) -> EngineContext:
    return EngineContext(
        symbol=str(symbol or ""),
        price=float(price or 0.0),
        market_mode=str(market_mode or "UNKNOWN").upper(),
        direction_policy=str(direction_policy or "UNKNOWN").upper(),
        box_state=str(box_state or "UNKNOWN").upper(),
        bb_state=str(bb_state or "UNKNOWN").upper(),
        box_low=None if box_low is None else float(box_low),
        box_high=None if box_high is None else float(box_high),
        bb20_up=None if bb20_up is None else float(bb20_up),
        bb20_mid=None if bb20_mid is None else float(bb20_mid),
        bb20_dn=None if bb20_dn is None else float(bb20_dn),
        bb44_up=None if bb44_up is None else float(bb44_up),
        bb44_mid=None if bb44_mid is None else float(bb44_mid),
        bb44_dn=None if bb44_dn is None else float(bb44_dn),
        ma20=None if ma20 is None else float(ma20),
        ma60=None if ma60 is None else float(ma60),
        ma120=None if ma120 is None else float(ma120),
        ma240=None if ma240 is None else float(ma240),
        ma480=None if ma480 is None else float(ma480),
        support=None if support is None else float(support),
        resistance=None if resistance is None else float(resistance),
        trendline_value=None if trendline_value is None else float(trendline_value),
        volatility_scale=None if volatility_scale is None else float(volatility_scale),
        metadata=dict(metadata or {}),
    )
