from __future__ import annotations

from copy import deepcopy


COMMON_EXPRESSION_POLICY_V1 = {
    "contract_version": "common_expression_policy_v1",
    "semantics": {
        "directional_wait_enabled": True,
        "soft_block_downgrades_ready": True,
        "structural_wait_recovery_enabled": True,
        "flat_exit_suppression_enabled": True,
        "terminal_exit_requires_position": True,
    },
    "readiness": {
        "confirm_floor_by_state": {
            "TREND_PULLBACK_BUY_CONFIRM": 0.03,
            "TREND_PULLBACK_SELL_CONFIRM": 0.03,
            "FAILED_SELL_RECLAIM_BUY_CONFIRM": 0.03,
            "MID_RECLAIM_CONFIRM": 0.035,
            "MID_REJECT_CONFIRM": 0.035,
            "LOWER_REBOUND_CONFIRM": 0.20,
            "UPPER_REJECT_CONFIRM": 0.20,
            "LOWER_FAIL_CONFIRM": 0.24,
            "UPPER_BREAK_CONFIRM": 0.24,
            "DEFAULT": 0.20,
        },
        "confirm_advantage_by_state": {
            "TREND_PULLBACK_BUY_CONFIRM": 0.003,
            "TREND_PULLBACK_SELL_CONFIRM": 0.003,
            "FAILED_SELL_RECLAIM_BUY_CONFIRM": 0.003,
            "MID_RECLAIM_CONFIRM": 0.01,
            "MID_REJECT_CONFIRM": 0.01,
            "LOWER_REBOUND_CONFIRM": 0.003,
            "DEFAULT": 0.02,
        },
        "directional_wait_min_support_by_side": {
            "BUY": 0.05,
            "SELL": 0.05,
        },
        "directional_wait_min_pair_gap_by_side": {
            "BUY": 0.02,
            "SELL": 0.02,
        },
    },
    "probe": {
        "default_floor_mult": 0.72,
        "default_advantage_mult": 0.25,
        "default_support_tolerance": 0.015,
        "upper_min_support_by_side": {
            "SELL": 0.16,
            "BUY": 0.18,
        },
        "upper_min_pair_gap_by_side": {
            "SELL": 0.03,
            "BUY": 0.04,
        },
        "lower_min_support_by_side": {
            "BUY": 0.22,
            "SELL": 0.26,
        },
        "lower_min_pair_gap_by_side": {
            "BUY": 0.12,
            "SELL": 0.18,
        },
        "promotion_gate_support_penalty": 0.08,
        "promotion_gate_pair_gap_penalty": 0.05,
        "blocked_quick_states": [
            "BLOCKED",
            "PROBE_CANDIDATE_BLOCKED",
        ],
    },
    "translation": {
        "neutral_block_guards": [
            "outer_band_guard",
            "forecast_guard",
            "middle_sr_anchor_guard",
            "barrier_guard",
        ],
        "structural_wait_recovery_guards": [
            "middle_sr_anchor_guard",
            "outer_band_guard",
        ],
        "structural_wait_recovery_reasons": [
            "outer_band_reversal_support_required_observe",
            "middle_sr_anchor_required_observe",
        ],
        "watch_reason_suffix_by_side": {
            "BUY": "buy_watch",
            "SELL": "sell_watch",
        },
        "conflict_reason_prefixes": ["conflict_"],
        "probe_promotion_gate_neutralization_enabled": True,
        "edge_pair_directional_wait_fallback_enabled": True,
        "scene_side_fallback_enabled": True,
    },
    "scoring": {
        "input_paths": [
            "observe_confirm_v2.confidence",
            "probe_candidate_support",
            "probe_pair_gap",
        ],
        "reduction": "max",
        "probe_ready_bonus": 0.05,
        "probe_ready_bonus_kinds": [
            "BUY_READY",
            "SELL_READY",
            "BUY_PROBE",
            "SELL_PROBE",
        ],
    },
    "strength": {
        "level_count": 10,
        "score_input_paths": [
            "observe_confirm_v2.confidence",
            "probe_candidate_support",
            "semantic_readiness_bridge_v1.final.buy_support",
            "semantic_readiness_bridge_v1.final.sell_support",
            "probe_pair_gap",
            "edge_pair_law_v1.pair_gap",
        ],
        "pair_gap_weight": 0.35,
        "probe_ready_bonus": 0.05,
        "block_penalty_by_guard": {
            "energy_soft_block": 0.08,
            "*_soft_block": 0.08,
            "probe_promotion_gate": 0.10,
            "forecast_guard": 0.12,
            "barrier_guard": 0.12,
            "middle_sr_anchor_guard": 0.15,
            "outer_band_guard": 0.15,
            "conflict_default": 0.24,
        },
        "bucket_edges": [0.05, 0.11, 0.18, 0.26, 0.35, 0.45, 0.58, 0.72, 0.86],
        "visual_binding": {
            "apply_event_kinds": [
                "BUY_WAIT",
                "SELL_WAIT",
                "BUY_BLOCKED",
                "SELL_BLOCKED",
                "BUY_PROBE",
                "SELL_PROBE",
                "BUY_READY",
                "SELL_READY",
            ],
            "color_apply_event_kinds": [
                "BUY_WAIT",
                "SELL_WAIT",
                "BUY_BLOCKED",
                "SELL_BLOCKED",
                "BUY_PROBE",
                "SELL_PROBE",
                "BUY_READY",
                "SELL_READY",
            ],
            "line_width_apply_event_kinds": [
                "BUY_WAIT",
                "SELL_WAIT",
                "BUY_BLOCKED",
                "SELL_BLOCKED",
                "BUY_PROBE",
                "SELL_PROBE",
                "BUY_READY",
                "SELL_READY",
            ],
            "brighten_target_color": 0x00FFFFFF,
            "dim_target_color": 0x00000000,
            "alpha_by_level": {
                1: 0.00,
                2: 0.00,
                3: 0.00,
                4: 0.00,
                5: 0.08,
                6: 0.14,
                7: 0.20,
                8: 0.26,
                9: 0.34,
                10: 0.40,
            },
            "line_width_by_level": {
                1: 2,
                2: 2,
                3: 2,
                4: 3,
                5: 3,
                6: 3,
                7: 3,
                8: 4,
                9: 4,
                10: 4,
            },
        },
    },
    "visual": {
        "base_color_by_event_kind": {
            "BUY_READY": 65280,
            "SELL_READY": 255,
            "BUY_PROBE": 0x00E6FF66,
            "SELL_PROBE": 0x000040FF,
            "BUY_WATCH": 0x00F5FF99,
            "SELL_WATCH": 0x000020FF,
            "BUY_WAIT": 0x00C8FF4D,
            "SELL_WAIT": 0x000060FF,
            "BUY_BLOCKED": 0x0090CC33,
            "SELL_BLOCKED": 0x000050CC,
            "WAIT": 13421772,
            "ENTER_BUY": 65407,
            "ENTER_SELL": 16711935,
            "EXIT_NOW": 26367,
            "REVERSE_READY": 16711808,
            "HOLD": 16776960,
        },
        "compact_history_kinds": [
            "BUY_PROBE",
            "SELL_PROBE",
            "BUY_WATCH",
            "SELL_WATCH",
            "BUY_WAIT",
            "SELL_WAIT",
            "BUY_BLOCKED",
            "SELL_BLOCKED",
            "WAIT",
            "HOLD",
        ],
        "marker_time_scale": 0.50,
        "marker_price_scale": 0.50,
        "probe_marker_time_scale": 0.50,
        "probe_marker_price_scale": 0.50,
        "neutral_marker_time_scale": 0.50,
        "neutral_marker_price_scale": 0.50,
        "display_repeat_thresholds": {
            "single": 0.70,
            "double": 0.80,
            "triple": 0.90,
        },
        "display_repeat_time_offset_scale": 0.36,
        "display_repeat_price_offset_scale": 0.22,
        "display_repeat_apply_event_kinds": [
            "BUY_WAIT",
            "SELL_WAIT",
            "BUY_BLOCKED",
            "SELL_BLOCKED",
            "BUY_PROBE",
            "SELL_PROBE",
            "BUY_READY",
            "SELL_READY",
            "BUY_WATCH",
            "SELL_WATCH",
        ],
        "wait_brightness_by_event_kind": {
            "BUY_WAIT": {
                "brighten_threshold": 0.30,
                "brighten_target_color": 0x00FFFFFF,
                "brighten_alpha_base": 0.18,
                "brighten_alpha_scale": 0.90,
                "brighten_alpha_cap": 0.38,
                "dim_threshold": 0.06,
                "dim_target_color": 0x00000000,
                "dim_alpha": 0.18,
            },
            "SELL_WAIT": {
                "brighten_threshold": 0.12,
                "brighten_target_color": 0x00FFFFFF,
                "brighten_alpha_base": 0.12,
                "brighten_alpha_scale": 0.78,
                "brighten_alpha_cap": 0.36,
                "dim_threshold": 0.06,
                "dim_target_color": 0x00000000,
                "dim_alpha": 0.10,
            },
            "BUY_BLOCKED": {
                "brighten_threshold": 0.30,
                "brighten_target_color": 0x00FFFFFF,
                "brighten_alpha_base": 0.18,
                "brighten_alpha_scale": 0.90,
                "brighten_alpha_cap": 0.38,
                "dim_threshold": 0.06,
                "dim_target_color": 0x00000000,
                "dim_alpha": 0.18,
            },
            "SELL_BLOCKED": {
                "brighten_threshold": 0.12,
                "brighten_target_color": 0x00FFFFFF,
                "brighten_alpha_base": 0.12,
                "brighten_alpha_scale": 0.78,
                "brighten_alpha_cap": 0.36,
                "dim_threshold": 0.06,
                "dim_target_color": 0x00000000,
                "dim_alpha": 0.10,
            },
        },
    },
    "display_modifier": {
        "contract_version": "common_state_aware_display_modifier_v1",
        "repeat_thresholds": {
            "single": 0.70,
            "double": 0.80,
            "triple": 0.90,
        },
        "importance_score_floors": {
            "medium": 0.82,
            "high": 0.91,
        },
        "strength_level": {
            "ready": 8,
            "probe": {
                "base": 6,
                "high": 7,
                "candidate_support_min": 0.40,
                "pair_gap_min": 0.18,
            },
            "observe": {
                "blocked": 5,
                "default": 4,
            },
            "blocked": {
                "visible": 5,
                "hidden": 3,
            },
        },
        "stage_score": {
            "ready": {
                "base": 0.92,
                "cap": 0.98,
                "level_start": 8,
                "level_scale": 0.02,
            },
            "probe": {
                "base": 0.82,
                "cap": 0.89,
                "level_start": 6,
                "level_scale": 0.04,
            },
            "observe": {
                "base": 0.72,
                "cap": 0.79,
                "level_start": 4,
                "level_scale": 0.03,
            },
            "blocked": {
                "base": 0.71,
                "cap": 0.79,
                "level_start": 3,
                "level_scale": 0.02,
            },
        },
        "bridge": {
            "awareness_keep": {
                "enabled": True,
                "blocked_by_allow": [
                    "outer_band_guard",
                    "middle_sr_anchor_guard",
                    "forecast_guard",
                    "barrier_guard",
                ],
                "action_none_allow": [
                    "observe_state_wait",
                    "probe_not_promoted",
                ],
                "minimum_act_vs_wait_bias": 0.46,
                "maximum_false_break_risk": 0.78,
                "restore_stage": "OBSERVE",
            },
        },
        "soft_caps": {
            "conflict_wait_hide": {
                "enabled": True,
                "reason_prefixes": ["conflict_"],
                "blocked_by_allow": [
                    "forecast_guard",
                    "barrier_guard",
                    "middle_sr_anchor_guard",
                    "outer_band_guard",
                ],
                "action_none_allow": ["observe_state_wait"],
                "require_probe_scene_absent": True,
                "suppress_display": True,
            },
            "structural_wait_hide_without_probe": {
                "enabled": True,
                "side_allow": ["BUY"],
                "observe_reason_allow": [
                    "outer_band_reversal_support_required_observe",
                    "middle_sr_anchor_required_observe",
                ],
                "blocked_by_allow": [
                    "outer_band_guard",
                    "middle_sr_anchor_guard",
                ],
                "action_none_allow": ["observe_state_wait"],
                "require_probe_scene_absent": True,
                "require_importance_source_absent": True,
                "suppress_display": True,
            },
            "sell_outer_band_wait_hide_without_probe": {
                "enabled": True,
                "side_allow": ["SELL"],
                "observe_reason_allow": [
                    "outer_band_reversal_support_required_observe",
                ],
                "blocked_by_allow": [
                    "outer_band_guard",
                ],
                "action_none_allow": ["observe_state_wait"],
                "require_probe_scene_absent": True,
                "require_importance_source_absent": True,
                "suppress_display": True,
            },
            "nas_sell_middle_anchor_wait_hide_without_probe": {
                "enabled": True,
                "symbol_allow": ["NAS100"],
                "side_allow": ["SELL"],
                "observe_reason_allow": [
                    "middle_sr_anchor_required_observe",
                ],
                "blocked_by_allow": [
                    "middle_sr_anchor_guard",
                ],
                "action_none_allow": ["observe_state_wait"],
                "require_probe_scene_absent": True,
                "require_importance_source_absent": True,
                "suppress_display": True,
            },
            "btc_sell_middle_anchor_wait_hide_without_probe": {
                "enabled": True,
                "symbol_allow": ["BTCUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": [
                    "middle_sr_anchor_required_observe",
                ],
                "blocked_by_allow": [
                    "middle_sr_anchor_guard",
                ],
                "action_none_allow": ["observe_state_wait"],
                "require_probe_scene_absent": True,
                "require_importance_source_absent": True,
                "suppress_display": True,
            },
            "nas_upper_reclaim_wait_hide_without_probe": {
                "enabled": True,
                "symbol_allow": ["NAS100"],
                "side_allow": ["BUY"],
                "observe_reason_allow": [
                    "upper_reclaim_strength_confirm",
                ],
                "blocked_by_allow": [
                    "forecast_guard",
                ],
                "action_none_allow": ["observe_state_wait"],
                "require_probe_scene_absent": True,
                "require_importance_source_absent": True,
                "suppress_display": True,
            },
            "xau_upper_reclaim_wait_hide_without_probe": {
                "enabled": True,
                "symbol_allow": ["XAUUSD"],
                "side_allow": ["BUY"],
                "observe_reason_allow": [
                    "upper_reclaim_strength_confirm",
                ],
                "blocked_by_allow": [
                    "forecast_guard",
                ],
                "action_none_allow": ["observe_state_wait"],
                "require_probe_scene_absent": True,
                "require_importance_source_absent": True,
                "suppress_display": True,
            },
            "nas_upper_reject_wait_hide_without_probe": {
                "enabled": True,
                "symbol_allow": ["NAS100"],
                "side_allow": ["SELL"],
                "observe_reason_allow": [
                    "upper_reject_confirm",
                ],
                "blocked_by_allow": [
                    "forecast_guard",
                ],
                "action_none_allow": ["observe_state_wait"],
                "require_probe_scene_absent": True,
                "require_importance_source_absent": True,
                "suppress_display": True,
            },
            "nas_upper_break_fail_wait_hide_without_probe": {
                "enabled": True,
                "symbol_allow": ["NAS100"],
                "side_allow": ["SELL"],
                "observe_reason_allow": [
                    "upper_break_fail_confirm",
                ],
                "blocked_by_allow": [
                    "forecast_guard",
                ],
                "action_none_allow": ["observe_state_wait"],
                "require_probe_scene_absent": True,
                "require_importance_source_absent": True,
                "suppress_display": True,
            },
            "btc_lower_rebound_forecast_wait_hide_without_probe": {
                "enabled": True,
                "symbol_allow": ["BTCUSD"],
                "side_allow": ["BUY"],
                "observe_reason_allow": [
                    "lower_rebound_confirm",
                ],
                "blocked_by_allow": [
                    "forecast_guard",
                ],
                "action_none_allow": ["observe_state_wait"],
                "importance_source_allow": ["btc_lower_recovery_start"],
                "require_probe_scene_absent": True,
                "suppress_display": True,
            },
        },
        "chart_wait_reliefs": {
            "probe_guard_wait_as_wait_checks": {
                "enabled": True,
                "observe_reason_allow": [
                    "outer_band_reversal_support_required_observe",
                    "middle_sr_anchor_required_observe",
                ],
                "blocked_by_allow": [
                    "outer_band_guard",
                    "middle_sr_anchor_guard",
                ],
                "action_none_allow": ["probe_not_promoted"],
                "require_probe_scene_present": True,
                "stage_allow": ["OBSERVE"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "probe_guard_wait_as_wait_checks",
            },
            "xau_upper_reject_mixed_guard_wait_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["XAUUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_reject_mixed_confirm"],
                "blocked_by_allow": ["barrier_guard", "forecast_guard"],
                "action_none_allow": ["observe_state_wait"],
                "require_probe_scene_absent": True,
                "stage_allow": ["PROBE", "OBSERVE"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "xau_upper_reject_mixed_guard_wait_as_wait_checks",
            },
            "xau_upper_reject_confirm_forecast_wait_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["XAUUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_reject_confirm"],
                "blocked_by_allow": ["forecast_guard"],
                "action_none_allow": ["observe_state_wait"],
                "require_probe_scene_absent": True,
                "stage_allow": ["PROBE", "OBSERVE"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "xau_upper_reject_confirm_forecast_wait_as_wait_checks",
            },
            "xau_middle_anchor_guard_wait_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["XAUUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["middle_sr_anchor_required_observe"],
                "blocked_by_allow": ["middle_sr_anchor_guard"],
                "action_none_allow": ["observe_state_wait"],
                "require_probe_scene_absent": True,
                "stage_allow": ["OBSERVE"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "xau_middle_anchor_guard_wait_as_wait_checks",
            },
            "xau_upper_reject_confirm_energy_soft_block_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["XAUUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_reject_confirm"],
                "blocked_by_allow": ["energy_soft_block"],
                "action_none_allow": ["execution_soft_blocked"],
                "require_probe_scene_absent": True,
                "stage_allow": ["BLOCKED"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "xau_upper_reject_confirm_energy_soft_block_as_wait_checks",
            },
            "xau_upper_reject_mixed_confirm_energy_soft_block_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["XAUUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_reject_mixed_confirm"],
                "blocked_by_allow": ["energy_soft_block"],
                "action_none_allow": ["execution_soft_blocked"],
                "require_probe_scene_absent": True,
                "stage_allow": ["BLOCKED"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "xau_upper_reject_mixed_confirm_energy_soft_block_as_wait_checks",
            },
            "xau_upper_reject_mixed_confirm_entry_gate_wait_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["XAUUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_reject_mixed_confirm"],
                "blocked_by_allow": [
                    "clustered_entry_price_zone",
                    "pyramid_not_progressed",
                    "pyramid_not_in_drawdown",
                ],
                "require_probe_scene_absent": True,
                "stage_allow": ["OBSERVE", "PROBE", "BLOCKED"],
                "restore_hidden_display": True,
                "restore_stage": "OBSERVE",
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "xau_upper_reject_mixed_confirm_entry_gate_wait_as_wait_checks",
            },
            "xau_upper_break_fail_confirm_energy_soft_block_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["XAUUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_break_fail_confirm"],
                "blocked_by_allow": ["energy_soft_block"],
                "action_none_allow": ["execution_soft_blocked"],
                "require_probe_scene_absent": True,
                "stage_allow": ["BLOCKED"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "xau_upper_break_fail_confirm_energy_soft_block_as_wait_checks",
            },
            "nas_upper_break_fail_confirm_energy_soft_block_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["NAS100"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_break_fail_confirm"],
                "blocked_by_allow": ["energy_soft_block"],
                "action_none_allow": ["execution_soft_blocked"],
                "require_probe_scene_absent": True,
                "stage_allow": ["BLOCKED"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "nas_upper_break_fail_confirm_energy_soft_block_as_wait_checks",
            },
            "nas_upper_break_fail_confirm_entry_gate_wait_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["NAS100"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_break_fail_confirm"],
                "blocked_by_allow": [
                    "clustered_entry_price_zone",
                    "pyramid_not_progressed",
                    "pyramid_not_in_drawdown",
                ],
                "require_probe_scene_absent": True,
                "stage_allow": ["OBSERVE", "PROBE", "BLOCKED"],
                "restore_hidden_display": True,
                "restore_stage": "OBSERVE",
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "nas_upper_break_fail_confirm_entry_gate_wait_as_wait_checks",
            },
            "nas_upper_reject_mixed_confirm_energy_soft_block_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["NAS100"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_reject_mixed_confirm"],
                "blocked_by_allow": ["energy_soft_block"],
                "action_none_allow": ["execution_soft_blocked"],
                "require_probe_scene_absent": True,
                "stage_allow": ["BLOCKED"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "nas_upper_reject_mixed_confirm_energy_soft_block_as_wait_checks",
            },
            "xau_upper_reject_probe_energy_soft_block_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["XAUUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_reject_probe_observe"],
                "blocked_by_allow": ["energy_soft_block"],
                "action_none_allow": ["execution_soft_blocked"],
                "probe_scene_allow": ["xau_upper_sell_probe"],
                "require_probe_scene_present": True,
                "stage_allow": ["PROBE", "BLOCKED"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "xau_upper_reject_probe_energy_soft_block_as_wait_checks",
            },
            "xau_middle_anchor_probe_energy_soft_block_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["XAUUSD"],
                "side_allow": ["BUY"],
                "observe_reason_allow": ["middle_sr_anchor_required_observe"],
                "blocked_by_allow": ["energy_soft_block"],
                "action_none_allow": ["execution_soft_blocked"],
                "probe_scene_allow": ["xau_second_support_buy_probe"],
                "require_probe_scene_present": True,
                "stage_allow": ["PROBE", "BLOCKED"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "xau_middle_anchor_probe_energy_soft_block_as_wait_checks",
            },
            "xau_outer_band_probe_energy_soft_block_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["XAUUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["outer_band_reversal_support_required_observe"],
                "blocked_by_allow": ["energy_soft_block"],
                "action_none_allow": ["execution_soft_blocked"],
                "probe_scene_allow": ["xau_upper_sell_probe"],
                "require_probe_scene_present": True,
                "stage_allow": ["PROBE", "BLOCKED"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "xau_outer_band_probe_energy_soft_block_as_wait_checks",
            },
            "xau_outer_band_probe_entry_gate_wait_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["XAUUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["outer_band_reversal_support_required_observe"],
                "blocked_by_allow": [
                    "clustered_entry_price_zone",
                    "pyramid_not_progressed",
                    "pyramid_not_in_drawdown",
                ],
                "probe_scene_allow": ["xau_upper_sell_probe"],
                "require_probe_scene_present": True,
                "stage_allow": ["OBSERVE", "PROBE", "BLOCKED"],
                "restore_hidden_display": True,
                "restore_stage": "OBSERVE",
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "xau_outer_band_probe_entry_gate_wait_as_wait_checks",
            },
            "xau_lower_probe_guard_wait_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["XAUUSD"],
                "side_allow": ["BUY"],
                "observe_reason_allow": ["lower_rebound_probe_observe"],
                "blocked_by_allow": ["forecast_guard", "barrier_guard"],
                "action_none_allow": ["probe_not_promoted"],
                "probe_scene_allow": ["xau_second_support_buy_probe"],
                "require_probe_scene_present": True,
                "stage_allow": ["OBSERVE", "PROBE"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "xau_lower_probe_guard_wait_as_wait_checks",
            },
            "btc_lower_probe_promotion_wait_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["BTCUSD"],
                "side_allow": ["BUY"],
                "observe_reason_allow": ["lower_rebound_probe_observe"],
                "blocked_by_allow": ["probe_promotion_gate"],
                "action_none_allow": ["probe_not_promoted"],
                "probe_scene_allow": ["btc_lower_buy_conservative_probe"],
                "require_probe_scene_present": True,
                "stage_allow": ["PROBE"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "btc_lower_probe_promotion_wait_as_wait_checks",
            },
            "btc_lower_probe_guard_wait_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["BTCUSD"],
                "side_allow": ["BUY"],
                "observe_reason_allow": ["lower_rebound_probe_observe"],
                "blocked_by_allow": ["forecast_guard", "barrier_guard"],
                "action_none_allow": ["probe_not_promoted"],
                "probe_scene_allow": ["btc_lower_buy_conservative_probe"],
                "require_probe_scene_present": True,
                "stage_allow": ["OBSERVE", "PROBE"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "btc_lower_probe_guard_wait_as_wait_checks",
            },
            "btc_upper_reject_confirm_forecast_wait_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["BTCUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_reject_confirm"],
                "blocked_by_allow": ["forecast_guard"],
                "action_none_allow": ["observe_state_wait"],
                "require_probe_scene_absent": True,
                "stage_allow": ["OBSERVE", "PROBE"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "btc_upper_reject_confirm_forecast_wait_as_wait_checks",
            },
            "btc_upper_break_fail_confirm_forecast_wait_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["BTCUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_break_fail_confirm"],
                "blocked_by_allow": ["forecast_guard"],
                "action_none_allow": ["observe_state_wait"],
                "require_probe_scene_absent": True,
                "stage_allow": ["OBSERVE", "PROBE"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "btc_upper_break_fail_confirm_forecast_wait_as_wait_checks",
            },
            "btc_upper_break_fail_confirm_entry_gate_wait_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["BTCUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_break_fail_confirm"],
                "blocked_by_allow": [
                    "clustered_entry_price_zone",
                    "pyramid_not_progressed",
                    "pyramid_not_in_drawdown",
                ],
                "require_probe_scene_absent": True,
                "stage_allow": ["OBSERVE", "PROBE", "BLOCKED"],
                "restore_hidden_display": True,
                "restore_stage": "OBSERVE",
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "btc_upper_break_fail_confirm_entry_gate_wait_as_wait_checks",
            },
            "btc_upper_break_fail_confirm_energy_soft_block_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["BTCUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_break_fail_confirm"],
                "blocked_by_allow": ["energy_soft_block"],
                "action_none_allow": ["execution_soft_blocked"],
                "require_probe_scene_absent": True,
                "stage_allow": ["BLOCKED"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "btc_upper_break_fail_confirm_energy_soft_block_as_wait_checks",
            },
            "btc_upper_reject_probe_forecast_wait_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["BTCUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_reject_probe_observe"],
                "blocked_by_allow": ["forecast_guard"],
                "action_none_allow": ["probe_not_promoted"],
                "probe_scene_allow": ["btc_upper_sell_probe"],
                "require_probe_scene_present": True,
                "stage_allow": ["PROBE"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "btc_upper_reject_probe_forecast_wait_as_wait_checks",
            },
            "btc_upper_reject_probe_preflight_wait_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["BTCUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_reject_probe_observe"],
                "blocked_by_allow": ["preflight_action_blocked"],
                "action_none_allow": ["preflight_blocked"],
                "probe_scene_allow": ["btc_upper_sell_probe"],
                "require_probe_scene_present": True,
                "stage_allow": ["BLOCKED"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "btc_upper_reject_probe_preflight_wait_as_wait_checks",
            },
            "btc_upper_reject_probe_promotion_wait_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["BTCUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_reject_probe_observe"],
                "blocked_by_allow": ["probe_promotion_gate"],
                "action_none_allow": ["probe_not_promoted"],
                "probe_scene_allow": ["btc_upper_sell_probe"],
                "require_probe_scene_present": True,
                "stage_allow": ["PROBE"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "btc_upper_reject_probe_promotion_wait_as_wait_checks",
            },
            "btc_upper_reject_confirm_preflight_wait_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["BTCUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_reject_confirm"],
                "blocked_by_allow": ["preflight_action_blocked"],
                "action_none_allow": ["preflight_blocked"],
                "require_probe_scene_absent": True,
                "stage_allow": ["BLOCKED"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "btc_upper_reject_confirm_preflight_wait_as_wait_checks",
            },
            "btc_upper_reject_confirm_energy_soft_block_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["BTCUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_reject_confirm"],
                "blocked_by_allow": ["energy_soft_block"],
                "action_none_allow": ["execution_soft_blocked"],
                "require_probe_scene_absent": True,
                "stage_allow": ["BLOCKED"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "btc_upper_reject_confirm_energy_soft_block_as_wait_checks",
            },
            "btc_upper_reject_mixed_confirm_energy_soft_block_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["BTCUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_reject_mixed_confirm"],
                "blocked_by_allow": ["energy_soft_block"],
                "action_none_allow": ["execution_soft_blocked"],
                "require_probe_scene_absent": True,
                "stage_allow": ["BLOCKED"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "btc_upper_reject_mixed_confirm_energy_soft_block_as_wait_checks",
            },
            "btc_upper_reject_probe_energy_soft_block_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["BTCUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_reject_probe_observe"],
                "blocked_by_allow": ["energy_soft_block"],
                "action_none_allow": ["execution_soft_blocked"],
                "probe_scene_allow": ["btc_upper_sell_probe"],
                "require_probe_scene_present": True,
                "stage_allow": ["PROBE", "BLOCKED"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "btc_upper_reject_probe_energy_soft_block_as_wait_checks",
            },
            "nas_upper_reject_probe_forecast_wait_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["NAS100"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_reject_probe_observe"],
                "blocked_by_allow": ["forecast_guard"],
                "action_none_allow": ["probe_not_promoted"],
                "probe_scene_allow": ["nas_clean_confirm_probe"],
                "require_probe_scene_present": True,
                "stage_allow": ["PROBE"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "nas_upper_reject_probe_forecast_wait_as_wait_checks",
            },
            "nas_upper_reject_probe_promotion_wait_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["NAS100"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_reject_probe_observe"],
                "blocked_by_allow": ["probe_promotion_gate"],
                "action_none_allow": ["probe_not_promoted"],
                "probe_scene_allow": ["nas_clean_confirm_probe"],
                "require_probe_scene_present": True,
                "stage_allow": ["PROBE"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "nas_upper_reject_probe_promotion_wait_as_wait_checks",
            },
            "xau_upper_reject_probe_forecast_wait_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["XAUUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_reject_probe_observe"],
                "blocked_by_allow": ["forecast_guard"],
                "action_none_allow": ["probe_not_promoted"],
                "probe_scene_allow": ["xau_upper_sell_probe"],
                "require_probe_scene_present": True,
                "stage_allow": ["PROBE"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "xau_upper_reject_probe_forecast_wait_as_wait_checks",
            },
            "xau_upper_reject_probe_promotion_wait_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["XAUUSD"],
                "side_allow": ["SELL"],
                "observe_reason_allow": ["upper_reject_probe_observe"],
                "blocked_by_allow": ["probe_promotion_gate"],
                "action_none_allow": ["probe_not_promoted"],
                "probe_scene_allow": ["xau_upper_sell_probe"],
                "require_probe_scene_present": True,
                "stage_allow": ["PROBE"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "xau_upper_reject_probe_promotion_wait_as_wait_checks",
            },
            "btc_lower_rebound_probe_energy_soft_block_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["BTCUSD"],
                "side_allow": ["BUY"],
                "observe_reason_allow": ["lower_rebound_probe_observe"],
                "blocked_by_allow": ["energy_soft_block"],
                "action_none_allow": ["execution_soft_blocked"],
                "probe_scene_allow": ["btc_lower_buy_conservative_probe"],
                "require_probe_scene_present": True,
                "stage_allow": ["PROBE", "BLOCKED"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "btc_lower_rebound_probe_energy_soft_block_as_wait_checks",
            },
            "btc_structural_probe_energy_soft_block_as_wait_checks": {
                "enabled": True,
                "symbol_allow": ["BTCUSD"],
                "side_allow": ["BUY"],
                "observe_reason_allow": ["outer_band_reversal_support_required_observe"],
                "blocked_by_allow": ["energy_soft_block"],
                "action_none_allow": ["execution_soft_blocked"],
                "probe_scene_allow": ["btc_lower_buy_conservative_probe"],
                "require_probe_scene_present": True,
                "stage_allow": ["PROBE", "BLOCKED"],
                "event_kind_hint": "WAIT",
                "display_mode": "wait_check_repeat",
                "display_reason": "btc_structural_probe_energy_soft_block_as_wait_checks",
            },
        },
    },
    "anchor": {
        "buy_upper_reclaim_mode": "body_low",
        "buy_middle_ratio": 0.48,
        "buy_probe_ratio": 0.30,
        "buy_default_ratio": 0.36,
        "sell_mode": "high",
        "neutral_mode": "close",
    },
}


def build_common_expression_policy_v1() -> dict:
    return deepcopy(COMMON_EXPRESSION_POLICY_V1)
